### ISSUE TITLE
This should be named vcloud-disk_launcher

### ISSUE THREAD

**Issue by mikepea** [alphagov/vcloud-disk_launcher#1]
The name of this repo is breaking from the vCloud Tools and Gem convention.

Can you rename (or recreate) it to be vcloud-disk_launcher please.

:cake: :beer: :eggplant:

**Comment by annashipman** [comment]
You are correct, it is! @mattbostock, the guidelines are [on the wiki wiki](https://github.com/alphagov/wiki/wiki/Gem-guidelines). I've renamed this repo: https://github.com/alphagov/vcloud-disk_launcher

**Comment by mattbostock** [comment]
@annashipman, did you mean to address Mike rather than me?

**Comment by mattbostock** [comment]
Please ignore my above comment, I've amended the README also.

**Comment by annashipman** [comment]
@mattbostock no, you, because I think you created this repo?

**Comment by annashipman** [comment]
Oops, just seen your second comment. Thanks!
